[2025-01-30T00:54:03.332+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-30T00:54:03.359+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: manage_airflow_roles.assign_permissions_dag manual__2025-01-30T00:44:42.164833+00:00 [queued]>
[2025-01-30T00:54:03.381+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: manage_airflow_roles.assign_permissions_dag manual__2025-01-30T00:44:42.164833+00:00 [queued]>
[2025-01-30T00:54:03.381+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 3
[2025-01-30T00:54:03.416+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): assign_permissions_dag> on 2025-01-30 00:44:42.164833+00:00
[2025-01-30T00:54:03.424+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1053) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-30T00:54:03.426+0000] {standard_task_runner.py:72} INFO - Started process 1055 to run task
[2025-01-30T00:54:03.428+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'manage_***_roles', 'assign_permissions_dag', 'manual__2025-01-30T00:44:42.164833+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpg6g4qu_4']
[2025-01-30T00:54:03.430+0000] {standard_task_runner.py:105} INFO - Job 50: Subtask assign_permissions_dag
[2025-01-30T00:54:03.649+0000] {task_command.py:467} INFO - Running <TaskInstance: manage_airflow_roles.assign_permissions_dag manual__2025-01-30T00:44:42.164833+00:00 [running]> on host 156798cb3511
[2025-01-30T00:54:03.717+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='manage_***_roles' AIRFLOW_CTX_TASK_ID='assign_permissions_dag' AIRFLOW_CTX_EXECUTION_DATE='2025-01-30T00:44:42.164833+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-30T00:44:42.164833+00:00'
[2025-01-30T00:54:03.718+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-30T00:54:03.718+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-30T00:54:03.719+0000] {logging_mixin.py:190} INFO - Current task name:assign_permissions_dag state:running start_date:2025-01-30 00:54:03.360174+00:00
[2025-01-30T00:54:03.719+0000] {logging_mixin.py:190} INFO - Dag name:manage_***_roles and current dag run status:running
[2025-01-30T00:54:03.719+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-30T00:54:03.720+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 129, in assign_permissions_dag
    permissions_list = list(permissions_list.keys())
                            ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'keys'
[2025-01-30T00:54:03.735+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-30T00:54:03.735+0000] {logging_mixin.py:190} INFO - Task start:2025-01-30 00:54:03.360174+00:00 end:2025-01-30 00:54:03.734535+00:00 duration:0.374361
[2025-01-30T00:54:03.736+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): assign_permissions_dag> dag:<DAG: manage_***_roles> dagrun:<DagRun manage_***_roles @ 2025-01-30 00:44:42.164833+00:00: manual__2025-01-30T00:44:42.164833+00:00, state:running, queued_at: 2025-01-30 00:54:01.773610+00:00. externally triggered: True>
[2025-01-30T00:54:03.736+0000] {logging_mixin.py:190} INFO - Failure caused by 'list' object has no attribute 'keys'
[2025-01-30T00:54:03.737+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=manage_***_roles, task_id=assign_permissions_dag, run_id=manual__2025-01-30T00:44:42.164833+00:00, execution_date=20250130T004442, start_date=20250130T005403, end_date=20250130T005403
[2025-01-30T00:54:03.754+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-30T00:54:03.755+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 50 for task assign_permissions_dag ('list' object has no attribute 'keys'; 1055)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 129, in assign_permissions_dag
    permissions_list = list(permissions_list.keys())
                            ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'keys'
[2025-01-30T00:54:03.802+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-30T00:54:03.977+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-30T00:54:03.979+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
