[2025-02-01T00:31:46.822+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-01T00:31:46.837+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: manage_airflow_roles.assign_generic_permissions_roles manual__2025-02-01T00:05:21.077807+00:00 [queued]>
[2025-02-01T00:31:46.846+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: manage_airflow_roles.assign_generic_permissions_roles manual__2025-02-01T00:05:21.077807+00:00 [queued]>
[2025-02-01T00:31:46.846+0000] {taskinstance.py:2866} INFO - Starting attempt 9 of 9
[2025-02-01T00:31:46.857+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): assign_generic_permissions_roles> on 2025-02-01 00:05:21.077807+00:00
[2025-02-01T00:31:46.862+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3914) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-01T00:31:46.863+0000] {standard_task_runner.py:72} INFO - Started process 3916 to run task
[2025-02-01T00:31:46.863+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'manage_***_roles', 'assign_generic_permissions_roles', 'manual__2025-02-01T00:05:21.077807+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp3z1hkg3y']
[2025-02-01T00:31:46.864+0000] {standard_task_runner.py:105} INFO - Job 120: Subtask assign_generic_permissions_roles
[2025-02-01T00:31:46.895+0000] {task_command.py:467} INFO - Running <TaskInstance: manage_airflow_roles.assign_generic_permissions_roles manual__2025-02-01T00:05:21.077807+00:00 [running]> on host dab0f5b0cfba
[2025-02-01T00:31:46.991+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='manage_***_roles' AIRFLOW_CTX_TASK_ID='assign_generic_permissions_roles' AIRFLOW_CTX_EXECUTION_DATE='2025-02-01T00:05:21.077807+00:00' AIRFLOW_CTX_TRY_NUMBER='9' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-01T00:05:21.077807+00:00'
[2025-02-01T00:31:46.992+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-01T00:31:50.421+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-01T00:31:53.719+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-01T00:31:57.023+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-02-01T00:31:57.024+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-01T00:31:57.025+0000] {process_utils.py:132} INFO - Sending 15 to group 3916. PIDs of all processes in the group: [3946, 3916]
[2025-02-01T00:31:57.025+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 3916
[2025-02-01T00:31:57.026+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-02-01T00:31:57.035+0000] {dag.py:163} INFO - Error assigning DAG Runs permissions to data-team
[2025-02-01T00:31:57.561+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3946, status='terminated', started='00:31:53') (3946) terminated with exit code None
[2025-02-01T00:32:00.588+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-01T00:32:04.323+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-01T00:32:08.183+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-01T00:32:12.652+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-01T00:32:15.805+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-01T00:32:19.097+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-01T00:32:22.929+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-01T00:32:26.199+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-01T00:32:29.576+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-01T00:32:33.193+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-01T00:32:36.240+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-01T00:32:39.591+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-01T00:32:43.037+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-01T00:32:46.466+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-01T00:32:49.876+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-01T00:32:52.997+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-01T00:32:56.579+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-01T00:32:57.054+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=3916, name='airflow task ru', status='sleeping', started='00:31:46') did not respond to SIGTERM. Trying SIGKILL
[2025-02-01T00:32:57.055+0000] {process_utils.py:87} INFO - Sending the signal 9 to group 3916
[2025-02-01T00:32:57.062+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3916, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='00:31:46') (3916) terminated with exit code -9
[2025-02-01T00:32:57.063+0000] {standard_task_runner.py:190} ERROR - ('Job 120 was killed before it finished (likely due to running out of memory)', 'For more information, see https://***.apache.org/docs/apache-***/stable/troubleshooting.html#LocalTaskJob-killed')
